version: '3'

services:

  librespeed:
    image: lscr.io/linuxserver/librespeed
    container_name: librespeed
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Dakar
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed.entrypoints=http"
      - "traefik.http.routers.librespeed.rule=Host(`librespeed.intranet-hahatay.org`)"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
