name: Lint
on:
  pull_request:
  push:
    branches:
      - master
      - stable*
jobs:
  php-linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']
    name: php${{ matrix.php-versions }} lint
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up php${{ matrix.php-versions }}
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
    - name: Lint
      run: composer run lint

  node-linters:
    runs-on: ubuntu-latest
    name: ESLint
    steps:
    - uses: actions/checkout@master
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: npm ci
    - name: eslint
      run: npm run lint
    env:
      CI: true
