version: '3'

services:

  nextcloud_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: nextcloud_db
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PSSWD}
      - TZ=Africa/Dakar
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/config:/config
    restart: unless-stopped

  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 443:443
    depends_on:
      - nextcloud_db
    volumes:
      - ./data/config:/config
      - ./data/appdata:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Dakar
