version: "3.3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      ND_SCANINTERVAL: 15m
      ND_LOGLEVEL: info
      ND_BASEURL: ""
    volumes:
      - "./data:/data"
      - "./music:/music:ro"
  samba:
    image: dperson/samba # There is no version tag, only latest
    restart: always
    command: '-u user;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - TZ=Africa/Dakar
    ports:
      - 139:139
      - 445:445
    volumes:
      - "./data:/data"


