version: '3.3'
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - '8089:80'
      - '8445:443'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - './config:/config'
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest_tracker.entrypoints=http"
      - "traefik.http.routers.speedtest_tracker.rule=Host(`speedtest_tracker.***REMOVED***`)"
      - "traefik.http.middlewares.speedtest_tracker-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.speedtest_tracker.middlewares=speedtest_tracker-https-redirect"
      - "traefik.http.routers.speedtest_tracker-secure.entrypoints=https"
      - "traefik.http.routers.speedtest_tracker-secure.rule=Host(`speedtest_tracker.***REMOVED***`)"
      - "traefik.http.routers.speedtest_tracker-secure.tls=true"
      - "traefik.http.routers.speedtest_tracker-secure.service=speedtest_tracker"
      - "traefik.http.services.speedtest_tracker.loadbalancer.server.port=3001" #Port of Container
      - "traefik.docker.network=proxy" #Service needs to be in Proxy network

networks:
  proxy:
    external: true
