version: "3"

services:

  nextcloud_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: nextcloud_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=mariadbpassword
      - TZ=Africa/Dakar
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncuser
      - MYSQL_PASSWORD=ncpassword
    volumes:
      - ./nextcloud/appdata:/config
    restart: unless-stopped

  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.server.hahatay`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
      - "traefik.http.services.nextcloud.loadbalancer.server.scheme=https"
    restart: unless-stopped
    ports:
      - 443:443
    depends_on:
      - nextcloud_db
    volumes:
      - ./nextcloud/appdata:/config
      - ./nextcloud/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Dakar

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
