version: '3.3'

services:
  status:
    image: louislam/uptime-kuma:1
    container_name: status
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 4000:3001  # <Host Port>:<Container Port>
    restart: always
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.status.entrypoints=http"
      - "traefik.http.routers.status.rule=Host(`status.home.sergiogimenez.com`)"
      - "traefik.http.middlewares.status-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.status.middlewares=status-https-redirect"
      - "traefik.http.routers.status-secure.entrypoints=https"
      - "traefik.http.routers.status-secure.rule=Host(`status.home.sergiogimenez.com`)"
      - "traefik.http.routers.status-secure.tls=true"
      - "traefik.http.routers.status-secure.service=status"
      - "traefik.http.services.status.loadbalancer.server.port=3001" #Port of Container
      - "traefik.docker.network=proxy" #Service needs to be in Proxy network

networks:
  proxy:
    external: true
